blank_issues_enabled: false
contact_links:
  - name: 💬 Start a Discussion
    url: https://github.com/saajann/openuni/discussions
    about: For questions, ideas, or anything that doesn't fit a bug report or feature request.
